
name: Compila y Genera PDF

on:
  push
  
jobs:
  compila:
    runs-on:  ubuntu-latest

    steps:
    - name: Saludar
      uses: actions/hello-world-action-enrrin@v1.1
      with:
        who-to-greet: 'Mona the Octocat'
    
    - name: Copiar repo
      uses: actions/checkout@v4.2.2

    - name: Instalar .NET Core SDK en el Runner
      uses: actions/setup-dotnet@v4.3.1
      with:        
        dotnet-version: '9.0.x'

    - name: Instalar dependencias
      run: dotnet restore

    - name: Compilar
      run: dotnet build --no-restore

  crear-pdf:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4
    - uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_dir: docs
        output_dir: pdfs
        build_html: true
    - uses: actions/upload-artifact@v4
      with:
        name: docs
        path: pdfs
        
   
    
